# Generated by Django 4.0.10 on 2023-04-01 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_alter_question_pub_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
    ]
